--- 
title: "Data Entry"
---

# Data Entry {#dataentry}

The Speedgoat website allows users to design sightability/composition surveys and enter survey data directly into the Speedgoat survey database.The data entry functionality requires users to set-up an abundance or composition survey using stratified sampling, and enter the resultant data from the survey so the survey design is saved with the survey data. The data can then be use in the sightability model and thus directly populate the IPM Database. To enter survey data, the user must 1) create a survey design and 2) enter data from the survey.

## Survey Design {#dataentry-survde}

The first step to entering survey data is to create a survey design. To get started click on **Data Entry** on the sidebar and then click **Survey Design** from the drop-down menu. To begin, you need to specify the **Species**, **DAU**, **Survey Type**, and **Survey Year** that you want to design. Once this information is entered, the map will zoom to the selected DAU showing the DAU and corresponding subunits. If the Subunits within the DAU have previously been stratified into High and Other strata, the strafication will be visible on the map, and in the table to the right of the map. To update the subunit's strafication, you have two options. 1) You can use the box in the upper right hand corner of the map titled **Click subunit to assign to:** to select a stratum you want to apply to a subunit, and then click the Subunit on the map. Once the subunit is clicked, it will change color to the selected stratum. Or, 2) you can use the table to the right of the map to change the strata.  By clicking in the stratum column next to the subunit you would like to change, you can select the desired strata from the drop-down menu. 

Once the DAU is correctly stratified, you can create a survey by clicking on the <span style="color: #004672;"><b>Sample Subunits</b></span> button. This will open a window allowing you to specify the time it take to fly one subunit, the proportion of each strata to sample, and the Sampling Method.The survey design tool allows you to randomly sample subunits within the DAU using either **Random** or **GRTS** sampling. GRTS (Generalized Random Tesselation Stratified) sampling is a spatially-balanced sampling framework. When changes are made in the **Time to fly one subunit** or the **Proportion of High to Sample**, these will result in changes in the Subunits to fly and the total flight time in the table at the bottom of the pop-up window. Once these decisions have been made, you can then click on the <span style="color: #004672;"><b>Sample</b></span> button. The subunits selected to be sampled with have a blue circle on the map and will have a check box in the **Selected** column of the table. You can then click on the <span style="color: #004672;"><b>Save Survey</b></span> button to save the survey. Once the survey is saved, you can view the survey details by clicking on the **Survey Details** button.

Once the survey is flown, you must confirm that all subunits selected to be flown in the survey design were in fact surveyed. allowing the sightability model to correctly extrapolate the results of the survey to the entire DAU. To record which subunits were surveyed, check the box in the **Surveyed** column by clicking on it.  This completes the survey design process.

